//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WCM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WCM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GUI.WCM", typeof(WCM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was reseted!.
        /// </summary>
        internal static string ApplicationReset {
            get {
                return ResourceManager.GetString("ApplicationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not colored!.
        /// </summary>
        internal static string ColorGraphErrorStatus {
            get {
                return ResourceManager.GetString("ColorGraphErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An algorithm is not selected. Please select some!.
        /// </summary>
        internal static string ColorGraphNoSelectedAlgorithm {
            get {
                return ResourceManager.GetString("ColorGraphNoSelectedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected algorithm.
        /// </summary>
        internal static string ColorGraphNoSelectedAlgorithmTitle {
            get {
                return ResourceManager.GetString("ColorGraphNoSelectedAlgorithmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is coloring!.
        /// </summary>
        internal static string ColorGraphProgressStatus {
            get {
                return ResourceManager.GetString("ColorGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong. The graph was not colored! Try it again!.
        /// </summary>
        internal static string ColorGraphSomethingWrong {
            get {
                return ResourceManager.GetString("ColorGraphSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not colored!.
        /// </summary>
        internal static string ColorGraphSomethingWrongStatus {
            get {
                return ResourceManager.GetString("ColorGraphSomethingWrongStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        internal static string ColorGraphSomethingWrongTitle {
            get {
                return ResourceManager.GetString("ColorGraphSomethingWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was colored..
        /// </summary>
        internal static string ColorGraphStatus {
            get {
                return ResourceManager.GetString("ColorGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s creating a complement graph..
        /// </summary>
        internal static string ComplementGraphProgressStatus {
            get {
                return ResourceManager.GetString("ComplementGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complement graph was created..
        /// </summary>
        internal static string ComplementGraphStatus {
            get {
                return ResourceManager.GetString("ComplementGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is generating..
        /// </summary>
        internal static string GenerateGraphProgressStatus {
            get {
                return ResourceManager.GetString("GenerateGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was generated..
        /// </summary>
        internal static string GenerateGraphStatus {
            get {
                return ResourceManager.GetString("GenerateGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is drawing!.
        /// </summary>
        internal static string GraphDrawingProgressStatus {
            get {
                return ResourceManager.GetString("GraphDrawingProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was drawn..
        /// </summary>
        internal static string GraphDrawingStatus {
            get {
                return ResourceManager.GetString("GraphDrawingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t remove the last vertex in the graph!.
        /// </summary>
        internal static string GraphModificationDeleteVertexOne {
            get {
                return ResourceManager.GetString("GraphModificationDeleteVertexOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove vertex.
        /// </summary>
        internal static string GraphModificationDeleteVertexOneTitle {
            get {
                return ResourceManager.GetString("GraphModificationDeleteVertexOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge already exists. Please choose another vertices names!.
        /// </summary>
        internal static string GraphModificationEdgeAlreadyExists {
            get {
                return ResourceManager.GetString("GraphModificationEdgeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge already exists.
        /// </summary>
        internal static string GraphModificationEdgeAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("GraphModificationEdgeAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge doesn&apos;t exist. Please select another vertices names!.
        /// </summary>
        internal static string GraphModificationEdgeDoesntExist {
            get {
                return ResourceManager.GetString("GraphModificationEdgeDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge doesn&apos;t exist.
        /// </summary>
        internal static string GraphModificationEdgeDoesntExistTitle {
            get {
                return ResourceManager.GetString("GraphModificationEdgeDoesntExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert vertices names for graph modification!.
        /// </summary>
        internal static string GraphModificationEdgeDoesntInserted {
            get {
                return ResourceManager.GetString("GraphModificationEdgeDoesntInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vertices name inserted.
        /// </summary>
        internal static string GraphModificationEdgeDoesntInsertedTitle {
            get {
                return ResourceManager.GetString("GraphModificationEdgeDoesntInsertedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is being modified.
        /// </summary>
        internal static string GraphModificationProgressStatus {
            get {
                return ResourceManager.GetString("GraphModificationProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was modified.
        /// </summary>
        internal static string GraphModificationStatus {
            get {
                return ResourceManager.GetString("GraphModificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex already exists. Please choose another vertex name!.
        /// </summary>
        internal static string GraphModificationVertexAlreadyExists {
            get {
                return ResourceManager.GetString("GraphModificationVertexAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex already exists.
        /// </summary>
        internal static string GraphModificationVertexAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex doesn&apos;t exist. Please select another vertex name!.
        /// </summary>
        internal static string GraphModificationVertexDoesntExist {
            get {
                return ResourceManager.GetString("GraphModificationVertexDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex doesn&apos;t exist.
        /// </summary>
        internal static string GraphModificationVertexDoesntExistTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexDoesntExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert vertex name for graph modification!.
        /// </summary>
        internal static string GraphModificationVertexDoesntInserted {
            get {
                return ResourceManager.GetString("GraphModificationVertexDoesntInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vertex name inserted.
        /// </summary>
        internal static string GraphModificationVertexDoesntInsertedTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexDoesntInsertedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose invalid vertex for this operation!.
        /// </summary>
        internal static string GraphModificationVertexInvalidVertex {
            get {
                return ResourceManager.GetString("GraphModificationVertexInvalidVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vertex.
        /// </summary>
        internal static string GraphModificationVertexInvalidVertexTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexInvalidVertexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a new vertex name for the vertex!.
        /// </summary>
        internal static string GraphModificationVertexNameDoesntInserted {
            get {
                return ResourceManager.GetString("GraphModificationVertexNameDoesntInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new vertex name inserted!.
        /// </summary>
        internal static string GraphModificationVertexNameDoesntInsertedTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexNameDoesntInsertedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists. Please choose something else!.
        /// </summary>
        internal static string GraphModificationVertexUserNameExists {
            get {
                return ResourceManager.GetString("GraphModificationVertexUserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        internal static string GraphModificationVertexUserNameExistsTitle {
            get {
                return ResourceManager.GetString("GraphModificationVertexUserNameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load a file with graph which you want to color!.
        /// </summary>
        internal static string GraphNoExists {
            get {
                return ResourceManager.GetString("GraphNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph no loaded.
        /// </summary>
        internal static string GraphNoExistsTitle {
            get {
                return ResourceManager.GetString("GraphNoExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s creating line graph..
        /// </summary>
        internal static string LineGraphProgressStatus {
            get {
                return ResourceManager.GetString("LineGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line graph was created..
        /// </summary>
        internal static string LineGraphStatus {
            get {
                return ResourceManager.GetString("LineGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create a line graph because the graph has 0 edges..
        /// </summary>
        internal static string LineGraphZeroEdges {
            get {
                return ResourceManager.GetString("LineGraphZeroEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line graph was not created.
        /// </summary>
        internal static string LineGraphZeroEdgesTitle {
            get {
                return ResourceManager.GetString("LineGraphZeroEdgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is invalid. Please load another one!.
        /// </summary>
        internal static string LoadGraphInvalidFile {
            get {
                return ResourceManager.GetString("LoadGraphInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not loaded!.
        /// </summary>
        internal static string LoadGraphInvalidFileStatus {
            get {
                return ResourceManager.GetString("LoadGraphInvalidFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string LoadGraphInvalidFileTitle {
            get {
                return ResourceManager.GetString("LoadGraphInvalidFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is invalid. Please load another one!.
        /// </summary>
        internal static string LoadGraphInvalidGraph {
            get {
                return ResourceManager.GetString("LoadGraphInvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not loaded..
        /// </summary>
        internal static string LoadGraphInvalidGraphStatus {
            get {
                return ResourceManager.GetString("LoadGraphInvalidGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid graph.
        /// </summary>
        internal static string LoadGraphInvalidGraphTitle {
            get {
                return ResourceManager.GetString("LoadGraphInvalidGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path doesn&apos;t exist! The graph was not loaded!.
        /// </summary>
        internal static string LoadGraphInvalidPath {
            get {
                return ResourceManager.GetString("LoadGraphInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not loaded!.
        /// </summary>
        internal static string LoadGraphInvalidPathStatus {
            get {
                return ResourceManager.GetString("LoadGraphInvalidPathStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        internal static string LoadGraphInvalidPathTitle {
            get {
                return ResourceManager.GetString("LoadGraphInvalidPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t support these files. We support only files with .graph..
        /// </summary>
        internal static string LoadGraphInvalidType {
            get {
                return ResourceManager.GetString("LoadGraphInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not loaded!.
        /// </summary>
        internal static string LoadGraphInvalidTypeStatus {
            get {
                return ResourceManager.GetString("LoadGraphInvalidTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type.
        /// </summary>
        internal static string LoadGraphInvalidTypeTitle {
            get {
                return ResourceManager.GetString("LoadGraphInvalidTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is loading!.
        /// </summary>
        internal static string LoadGraphProgressStatus {
            get {
                return ResourceManager.GetString("LoadGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was loaded..
        /// </summary>
        internal static string LoadGraphStatus {
            get {
                return ResourceManager.GetString("LoadGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is creating..
        /// </summary>
        internal static string NewGraphProgressStatus {
            get {
                return ResourceManager.GetString("NewGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was created..
        /// </summary>
        internal static string NewGraphStatus {
            get {
                return ResourceManager.GetString("NewGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties are calculating..
        /// </summary>
        internal static string PropertyProgressStatus {
            get {
                return ResourceManager.GetString("PropertyProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties were calculated..
        /// </summary>
        internal static string PropertyStatus {
            get {
                return ResourceManager.GetString("PropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image was not saved!.
        /// </summary>
        internal static string SaveImageSomethingWrong {
            get {
                return ResourceManager.GetString("SaveImageSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        internal static string SaveImageSomethingWrongTitle {
            get {
                return ResourceManager.GetString("SaveImageSomethingWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was saved..
        /// </summary>
        internal static string WriteGraph {
            get {
                return ResourceManager.GetString("WriteGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path doesn&apos;t exist! The graph was not saved!.
        /// </summary>
        internal static string WriteGraphInvalidPath {
            get {
                return ResourceManager.GetString("WriteGraphInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not saved!.
        /// </summary>
        internal static string WriteGraphInvalidPathStatus {
            get {
                return ResourceManager.GetString("WriteGraphInvalidPathStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        internal static string WriteGraphInvalidPathTitle {
            get {
                return ResourceManager.GetString("WriteGraphInvalidPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph isn&apos;t colored. Please, color the graph..
        /// </summary>
        internal static string WriteGraphNotColored {
            get {
                return ResourceManager.GetString("WriteGraphNotColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph isn&apos;t colored!.
        /// </summary>
        internal static string WriteGraphNotColoredTitle {
            get {
                return ResourceManager.GetString("WriteGraphNotColoredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is saving.
        /// </summary>
        internal static string WriteGraphProgressStatus {
            get {
                return ResourceManager.GetString("WriteGraphProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong. The graph was not saved! Try it again!.
        /// </summary>
        internal static string WriteGraphSomethingWrong {
            get {
                return ResourceManager.GetString("WriteGraphSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was not saved!.
        /// </summary>
        internal static string WriteGraphSomethingWrongStatus {
            get {
                return ResourceManager.GetString("WriteGraphSomethingWrongStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        internal static string WriteGraphSomethingWrongTitle {
            get {
                return ResourceManager.GetString("WriteGraphSomethingWrongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph was saved..
        /// </summary>
        internal static string WriteGraphStatus {
            get {
                return ResourceManager.GetString("WriteGraphStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved graph.
        /// </summary>
        internal static string WriteGraphTitle {
            get {
                return ResourceManager.GetString("WriteGraphTitle", resourceCulture);
            }
        }
    }
}
