//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.ReaderWriter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReaderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReaderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.ReaderWriter.Tests.ReaderResource", typeof(ReaderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidBallast1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidBallast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidBallast2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidBallast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidBallast3 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidBallast3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH2
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidColoredGraph {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidColoredGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCoreData1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCoreData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCoreData2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCoreData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices2: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCountVertices1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCountVertices1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: -1
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCountVertices2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCountVertices2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: a
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCountVertices3 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCountVertices3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidCountVertices4 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidCountVertices4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH2
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidGraph {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name2: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidGraphName {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation2: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidHeader1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList2
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidHeader2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Number of colors2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidNumberColors {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm2: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListInvalidUsedAlgorithm {
            get {
                return ResourceManager.GetString("GraphAdjacencyListInvalidUsedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListValidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphAdjacencyListValidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///(5)
        ///(7)
        ///1
        ///(6)
        ///(8)
        ///2
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///5
        ///(6)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListValidNumberColors {
            get {
                return ResourceManager.GetString("GraphAdjacencyListValidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///nula
        ///(číslo pět)
        ///(7)
        ///1
        ///(šest)
        ///(8)
        ///číslo dva
        ///(3)
        ///(7)
        ///3
        ///(8)
        ///4
        ///(9)
        ///číslo pět
        ///(šest)
        ///8
        ///(9)
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyListValidVertexName {
            get {
                return ResourceManager.GetString("GraphAdjacencyListValidVertexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidBallast1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidBallast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidBallast2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidBallast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidBallast3 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidBallast3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH2
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidColoredGraph {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidColoredGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///2 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCoreData1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCoreData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCoreData2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCoreData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCoreData3 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCoreData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCoreData4 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCoreData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices2: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCountVertices1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCountVertices1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: -1
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCountVertices2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCountVertices2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: a
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCountVertices3 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCountVertices3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidCountVertices4 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidCountVertices4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH2
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidGraph {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name2: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidGraphName {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation2: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidHeader1 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix2
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidHeader2 {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Number of colors2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidNumberColors {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm2: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixInvalidUsedAlgorithm {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixInvalidUsedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixValidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixValidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 0 0 0 0 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 1 0
        ///0 0 0 1 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 0 0 1
        ///1 0 0 0 0 0 1 0 0 0
        ///0 1 0 0 0 1 0 0 0 0
        ///1 0 1 0 0 0 0 0 0 0
        ///0 1 0 1 0 0 0 0 0 1
        ///0 0 0 0 1 0 0 0 1 0
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphAdjacencyMatrixValidNumberColors {
            get {
                return ResourceManager.GetString("GraphAdjacencyMatrixValidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidBallast1 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidBallast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidBallast2 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidBallast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidBallast3 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidBallast3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Chromatic number2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH2
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidColoredGraph {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidColoredGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCoreData1 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCoreData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5 1
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCoreData2 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCoreData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///(Zapomnel na zavorky)
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCoreData3 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCoreData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///(Zapomnel na zavorku 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCoreData4 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCoreData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices2: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCountVertices1 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCountVertices1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: -1
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCountVertices2 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCountVertices2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: a
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCountVertices3 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCountVertices3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidCountVertices4 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidCountVertices4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH2
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidGraph {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name2: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidGraphName {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation2: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidHeader1 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList2
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidHeader2 {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors2: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidNumberColors {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///(nula) (číslo pět)
        ///(nula) 7
        ///1 (šest)
        ///1 8
        ///(číslo dva) 3
        ///(číslo dva) 7
        ///3 8
        ///4 9
        ///(číslo pět) (šest)
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm2: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListInvalidUsedAlgorithm {
            get {
                return ResourceManager.GetString("GraphEdgeListInvalidUsedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: 
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListValidChromaticNumber {
            get {
                return ResourceManager.GetString("GraphEdgeListValidChromaticNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///0 5
        ///0 7
        ///1 6
        ///1 8
        ///2 3
        ///2 7
        ///3 8
        ///4 9
        ///5 6
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListValidNumberColors {
            get {
                return ResourceManager.GetString("GraphEdgeListValidNumberColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: edgeList
        ///
        ///Graph name: Graph name
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///(nula) (číslo pět)
        ///(nula) 7
        ///1 (šest)
        ///1 8
        ///(číslo dva) 3
        ///(číslo dva) 7
        ///3 8
        ///4 9
        ///(číslo pět) (šest)
        ///8 9
        ///
        ///COLORED GRAPH
        ///Number of colors: 3
        ///Used algorithm: optimal
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string GraphEdgeListValidVertexName {
            get {
                return ResourceManager.GetString("GraphEdgeListValidVertexName", resourceCulture);
            }
        }
    }
}
