//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.ReaderWriter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WriterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WriterResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.ReaderWriter.Tests.WriterResource", typeof(WriterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///0 1 1 1 0 0
        ///1 0 0 0 0 0
        ///1 0 0 0 0 0
        ///1 0 0 0 1 1
        ///0 0 0 1 0 0
        ///0 0 0 1 0 0
        ///
        ///COLORED GRAPH
        ///Number of colors: 2
        ///Used algorithm: randomSequence
        ///- 1
        ///-- 827 (827) 
        ///-- 831 (831) 
        ///-- 832 (832) 
        ///- 2
        ///-- 830 (830) 
        ///-- 829 (829) 
        ///-- 828 (828) 
        ///
        ///Number of colors: 2
        ///Used algorithm: largestFirstSequence
        ///- 1
        ///-- 842 (842) 
        ///-- 841 (841) 
        ///-- 840 (840) 
        ///- 2
        ///-- 839 (839) 
        ///-- 844 (844) 
        ///-- 843 (843 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graph1 {
            get {
                return ResourceManager.GetString("graph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///0 1 1 1 0 0
        ///1 0 0 0 0 0
        ///1 0 0 0 0 0
        ///1 0 0 0 1 1
        ///0 0 0 1 0 0
        ///0 0 0 1 0 0
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string graph2 {
            get {
                return ResourceManager.GetString("graph2", resourceCulture);
            }
        }
    }
}
