//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.Graph.GraphClass.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.Graph.GraphClass.Tests.ClassResource", typeof(ClassResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///0 1 0 1 0 1
        ///1 0 1 0 1 0
        ///0 1 0 1 0 1
        ///1 0 1 0 1 0
        ///0 1 0 1 0 1
        ///1 0 1 0 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass1 {
            get {
                return ResourceManager.GetString("graphClass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///0 1 1 1 1
        ///1 0 1 1 1
        ///1 1 0 1 1
        ///1 1 1 0 1
        ///1 1 1 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass2 {
            get {
                return ResourceManager.GetString("graphClass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 14
        ///
        ///GRAPH
        ///0 1 1 0 0 0 0 0 0 0 0 0 0 0
        ///1 0 0 1 1 0 0 0 0 0 0 0 0 0
        ///1 0 0 0 0 1 1 0 0 0 0 0 0 0
        ///0 1 0 0 0 0 0 1 1 0 0 0 0 0
        ///0 1 0 0 0 0 0 0 0 1 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 1 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 1 1
        ///0 0 0 1 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 1 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 1 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 1 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 1 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graphClass3 {
            get {
                return ResourceManager.GetString("graphClass3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 16
        ///
        ///GRAPH
        ///0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
        ///1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0
        ///1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0
        ///1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
        ///1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
        ///0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graphClass4 {
            get {
                return ResourceManager.GetString("graphClass4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///0 1 1 0 0
        ///1 0 0 1 0
        ///1 0 0 0 1
        ///0 1 0 0 1
        ///0 0 1 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass5 {
            get {
                return ResourceManager.GetString("graphClass5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///0 1 1 1 0
        ///1 0 0 1 0
        ///1 0 0 0 1
        ///1 1 0 0 1
        ///0 0 1 1 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass6 {
            get {
                return ResourceManager.GetString("graphClass6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///0 1 0 0 0 1
        ///1 0 1 0 0 0
        ///0 1 0 0 0 0
        ///0 0 0 0 1 0
        ///0 0 0 1 0 0
        ///1 0 0 0 0 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass7 {
            get {
                return ResourceManager.GetString("graphClass7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyMatrix
        ///
        ///Graph name: Name
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///0 1 0 0 0 1
        ///1 0 1 0 0 0
        ///0 1 0 1 0 0
        ///0 0 1 0 1 1
        ///0 0 0 1 0 0
        ///1 0 0 1 0 0
        ///
        ///COLORED GRAPH
        ///Chromatic number: 3
        ///Used algorithm: XXX
        ///0 -&gt; 0
        ///1 -&gt; 0
        ///2 -&gt; 0
        ///3 -&gt; 1
        ///4 -&gt; 0
        ///5 -&gt; 1
        ///6 -&gt; 2
        ///7 -&gt; 1
        ///8 -&gt; 2
        ///9 -&gt; 3.
        /// </summary>
        internal static string graphClass8 {
            get {
                return ResourceManager.GetString("graphClass8", resourceCulture);
            }
        }
    }
}
