//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompleteGraphsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompleteGraphsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources.CompleteGraphsResource", typeof(CompleteGraphsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K1
        ///Number of vertices: 1
        ///
        ///GRAPH
        ///1
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K1 {
            get {
                return ResourceManager.GetString("K1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K2
        ///Number of vertices: 2
        ///
        ///GRAPH
        ///2
        ///(1)
        ///1
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K2 {
            get {
                return ResourceManager.GetString("K2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K3
        ///Number of vertices: 3
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///1
        ///(2)
        ///(3)
        ///3
        ///(1)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K3 {
            get {
                return ResourceManager.GetString("K3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K4
        ///Number of vertices: 4
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K4 {
            get {
                return ResourceManager.GetString("K4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K5
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///(5)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(5)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K5 {
            get {
                return ResourceManager.GetString("K5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K6
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(5)
        ///(6)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///(5)
        ///(6)
        ///5
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(6)
        ///6
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K6 {
            get {
                return ResourceManager.GetString("K6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K7
        ///Number of vertices: 7
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///(5)
        ///(6)
        ///(7)
        ///5
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(6)
        ///(7)
        ///6
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(7)
        ///7
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K7 {
            get {
                return ResourceManager.GetString("K7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: K8
        ///Number of vertices: 8
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///5
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(6)
        ///(7)
        ///(8)
        ///6
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(7)
        ///(8)
        ///7
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(8)
        ///8
        ///(1)
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string K8 {
            get {
                return ResourceManager.GetString("K8", resourceCulture);
            }
        }
    }
}
