//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CycleGraphsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CycleGraphsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources.CycleGraphsResource", typeof(CycleGraphsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: C3
        ///Number of vertices: 3
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///2
        ///(1)
        ///(3)
        ///3
        ///(1)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: C4
        ///Number of vertices: 4
        ///
        ///GRAPH
        ///4
        ///(3)
        ///(1)
        ///1
        ///(2)
        ///(4)
        ///2
        ///(1)
        ///(3)
        ///3
        ///(2)
        ///(4)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: C5
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///4
        ///(3)
        ///(5)
        ///1
        ///(2)
        ///(5)
        ///2
        ///(1)
        ///(3)
        ///3
        ///(2)
        ///(4)
        ///5
        ///(4)
        ///(1)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: C6
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///4
        ///(3)
        ///(5)
        ///1
        ///(2)
        ///(6)
        ///2
        ///(1)
        ///(3)
        ///3
        ///(2)
        ///(4)
        ///5
        ///(4)
        ///(6)
        ///6
        ///(5)
        ///(1)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string C6 {
            get {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }
    }
}
