//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamedGraphsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamedGraphsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources.NamedGraphsResource", typeof(NamedGraphsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Bidiakis cube
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(7)
        ///2
        ///(1)
        ///(4)
        ///(9)
        ///3
        ///(4)
        ///(1)
        ///(5)
        ///4
        ///(3)
        ///(2)
        ///(6)
        ///5
        ///(6)
        ///(3)
        ///(10)
        ///6
        ///(5)
        ///(4)
        ///(12)
        ///7
        ///(8)
        ///(10)
        ///(1)
        ///8
        ///(7)
        ///(9)
        ///(11)
        ///9
        ///(8)
        ///(12)
        ///(2)
        ///10
        ///(11)
        ///(7)
        ///(5)
        ///11
        ///(10)
        ///(12)
        ///(8)
        ///12
        ///(11)
        ///(9)
        ///(6)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string BidiakisCube {
            get {
                return ResourceManager.GetString("BidiakisCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Bull graph
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///1
        ///(3)
        ///2
        ///(4)
        ///3
        ///(1)
        ///(4)
        ///(5)
        ///4
        ///(2)
        ///(3)
        ///(5)
        ///5
        ///(3)
        ///(4)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string BullGraph {
            get {
                return ResourceManager.GetString("BullGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Butterfly graph
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///1
        ///(3)
        ///(4)
        ///2
        ///(3)
        ///(5)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(5)
        ///4
        ///(1)
        ///(3)
        ///5
        ///(2)
        ///(3)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string ButterflyGraph {
            get {
                return ResourceManager.GetString("ButterflyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Chvátal graph
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(5)
        ///(11)
        ///2
        ///(1)
        ///(4)
        ///(6)
        ///(12)
        ///3
        ///(1)
        ///(4)
        ///(8)
        ///(10)
        ///4
        ///(2)
        ///(3)
        ///(7)
        ///(9)
        ///5
        ///(1)
        ///(7)
        ///(8)
        ///(10)
        ///6
        ///(2)
        ///(8)
        ///(7)
        ///(9)
        ///7
        ///(11)
        ///(4)
        ///(5)
        ///(6)
        ///8
        ///(12)
        ///(3)
        ///(5)
        ///(6)
        ///9
        ///(11)
        ///(4)
        ///(6)
        ///(10)
        ///10
        ///(12)
        ///(3)
        ///(5)
        ///(9)
        ///11
        ///(1)
        ///(7)
        ///(9)
        ///(12)
        ///12
        ///(2)
        ///(11)
        ///(8)
        ///(10)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string ChvatalGraph {
            get {
                return ResourceManager.GetString("ChvatalGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Diamond graph
        ///Number of vertices: 4
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///2
        ///(1)
        ///(4)
        ///3
        ///(1)
        ///(4)
        ///4
        ///(1)
        ///(2)
        ///(3)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string DiamondGraph {
            get {
                return ResourceManager.GetString("DiamondGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Dürer graph
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(5)
        ///2
        ///(1)
        ///(4)
        ///(8)
        ///3
        ///(1)
        ///(7)
        ///(9)
        ///4
        ///(2)
        ///(6)
        ///(10)
        ///5
        ///(1)
        ///(6)
        ///(11)
        ///6
        ///(4)
        ///(5)
        ///(10)
        ///7
        ///(3)
        ///(9)
        ///(8)
        ///8
        ///(2)
        ///(7)
        ///(12)
        ///9
        ///(3)
        ///(7)
        ///(11)
        ///10
        ///(4)
        ///(6)
        ///(12)
        ///11
        ///(5)
        ///(9)
        ///(12)
        ///12
        ///(8)
        ///(10)
        ///(11)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string DurerGraph {
            get {
                return ResourceManager.GetString("DurerGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Errera graph
        ///Number of vertices: 17
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(9)
        ///2
        ///(1)
        ///(4)
        ///(5)
        ///(7)
        ///(8)
        ///3
        ///(1)
        ///(5)
        ///(6)
        ///(10)
        ///(11)
        ///4
        ///(1)
        ///(2)
        ///(7)
        ///(9)
        ///(12)
        ///5
        ///(1)
        ///(2)
        ///(3)
        ///(8)
        ///(10)
        ///(13)
        ///6
        ///(1)
        ///(3)
        ///(9)
        ///(11)
        ///(14)
        ///7
        ///(2)
        ///(4)
        ///(8)
        ///(12)
        ///(15)
        ///8
        ///(2)
        ///(5)
        ///(7)
        ///(13)
        ///(15)
        ///9
        ///(1)
        ///(4)
        ///(6)
        ///(12)
        ///(14)
        ///(16)
        ///10
        ///(3)
        ///(5)
        ///(11)
        ///(13)
        ///(17)
        ///11
        ///(3)
        ///(6)
        ///(10)
        ///(14)
        ///(17)
        ///12
        ///(4)
        ///(7)
        ///(9)
        ///(15)
        ///(16)
        ///13
        ///(5)
        ///(8)
        ///(10)
        ///(1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErreraGraph {
            get {
                return ResourceManager.GetString("ErreraGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Franklin graph
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(3)
        ///(2)
        ///(5)
        ///2
        ///(1)
        ///(4)
        ///(8)
        ///3
        ///(1)
        ///(6)
        ///(10)
        ///4
        ///(2)
        ///(7)
        ///(9)
        ///5
        ///(1)
        ///(6)
        ///(11)
        ///6
        ///(3)
        ///(5)
        ///(7)
        ///7
        ///(4)
        ///(6)
        ///(8)
        ///8
        ///(2)
        ///(7)
        ///(12)
        ///9
        ///(4)
        ///(10)
        ///(11)
        ///10
        ///(3)
        ///(9)
        ///(12)
        ///11
        ///(5)
        ///(9)
        ///(12)
        ///12
        ///(8)
        ///(10)
        ///(11)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string FranklinGraph {
            get {
                return ResourceManager.GetString("FranklinGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Frucht graph
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(9)
        ///(7)
        ///2
        ///(1)
        ///(3)
        ///(11)
        ///3
        ///(2)
        ///(4)
        ///(11)
        ///4
        ///(3)
        ///(5)
        ///(12)
        ///5
        ///(4)
        ///(6)
        ///(12)
        ///6
        ///(5)
        ///(8)
        ///(7)
        ///7
        ///(1)
        ///(8)
        ///(6)
        ///8
        ///(6)
        ///(9)
        ///(7)
        ///9
        ///(1)
        ///(8)
        ///(10)
        ///10
        ///(9)
        ///(11)
        ///(12)
        ///11
        ///(2)
        ///(3)
        ///(10)
        ///12
        ///(4)
        ///(5)
        ///(10)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string FruchtGraph {
            get {
                return ResourceManager.GetString("FruchtGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Goldner–Harary graph
        ///Number of vertices: 11
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///(11)
        ///2
        ///(1)
        ///(5)
        ///(6)
        ///3
        ///(1)
        ///(6)
        ///(7)
        ///4
        ///(1)
        ///(5)
        ///(11)
        ///5
        ///(1)
        ///(2)
        ///(4)
        ///(6)
        ///(9)
        ///(11)
        ///6
        ///(1)
        ///(2)
        ///(3)
        ///(5)
        ///(7)
        ///(9)
        ///(10)
        ///(11)
        ///7
        ///(1)
        ///(3)
        ///(6)
        ///(8)
        ///(10)
        ///(11)
        ///8
        ///(1)
        ///(7)
        ///(11)
        ///9
        ///(5)
        ///(6)
        ///(11)
        ///10
        ///(6)
        ///(7)
        ///(11)
        ///11
        ///(1)
        ///(4)
        ///(5)
        ///(7)
        ///(8)
        ///(9)
        ///(10)
        ///(6)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string Goldner_HararyGraph {
            get {
                return ResourceManager.GetString("Goldner_HararyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Golomb graph
        ///Number of vertices: 10
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(9)
        ///(10)
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///(5)
        ///3
        ///(2)
        ///(5)
        ///(6)
        ///4
        ///(2)
        ///(5)
        ///(7)
        ///5
        ///(3)
        ///(4)
        ///(6)
        ///(7)
        ///(8)
        ///(2)
        ///6
        ///(3)
        ///(5)
        ///(8)
        ///(9)
        ///7
        ///(4)
        ///(5)
        ///(8)
        ///(10)
        ///8
        ///(5)
        ///(6)
        ///(7)
        ///9
        ///(1)
        ///(6)
        ///(10)
        ///10
        ///(1)
        ///(7)
        ///(9)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string GolombGraph {
            get {
                return ResourceManager.GetString("GolombGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Grötzsch graph
        ///Number of vertices: 11
        ///
        ///GRAPH
        ///2
        ///(1)
        ///(4)
        ///(7)
        ///1
        ///(2)
        ///(3)
        ///(9)
        ///(11)
        ///3
        ///(1)
        ///(7)
        ///(5)
        ///4
        ///(2)
        ///(6)
        ///(5)
        ///(9)
        ///5
        ///(3)
        ///(4)
        ///(8)
        ///(11)
        ///6
        ///(4)
        ///(7)
        ///(11)
        ///7
        ///(2)
        ///(3)
        ///(6)
        ///(8)
        ///(10)
        ///8
        ///(5)
        ///(7)
        ///(9)
        ///9
        ///(1)
        ///(4)
        ///(8)
        ///(10)
        ///10
        ///(7)
        ///(9)
        ///(11)
        ///11
        ///(1)
        ///(5)
        ///(6)
        ///(10)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string GrotzschGraph {
            get {
                return ResourceManager.GetString("GrotzschGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Herschel graph
        ///Number of vertices: 11
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(8)
        ///2
        ///(1)
        ///(5)
        ///(6)
        ///3
        ///(1)
        ///(6)
        ///(7)
        ///4
        ///(1)
        ///(5)
        ///(11)
        ///5
        ///(2)
        ///(4)
        ///(9)
        ///6
        ///(2)
        ///(3)
        ///(9)
        ///(10)
        ///7
        ///(3)
        ///(10)
        ///(8)
        ///8
        ///(1)
        ///(7)
        ///(11)
        ///9
        ///(5)
        ///(6)
        ///(11)
        ///10
        ///(6)
        ///(7)
        ///(11)
        ///11
        ///(4)
        ///(8)
        ///(9)
        ///(10)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string HerschelGraph {
            get {
                return ResourceManager.GetString("HerschelGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Hoffman graph
        ///Number of vertices: 16
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(5)
        ///(6)
        ///2
        ///(1)
        ///(4)
        ///(7)
        ///(8)
        ///3
        ///(1)
        ///(4)
        ///(9)
        ///(10)
        ///4
        ///(2)
        ///(3)
        ///(11)
        ///(12)
        ///5
        ///(1)
        ///(7)
        ///(8)
        ///(13)
        ///6
        ///(1)
        ///(9)
        ///(10)
        ///(13)
        ///7
        ///(2)
        ///(5)
        ///(11)
        ///(14)
        ///8
        ///(2)
        ///(5)
        ///(12)
        ///(15)
        ///9
        ///(3)
        ///(6)
        ///(11)
        ///(14)
        ///10
        ///(3)
        ///(6)
        ///(12)
        ///(15)
        ///11
        ///(4)
        ///(7)
        ///(9)
        ///(16)
        ///12
        ///(4)
        ///(8)
        ///(10)
        ///(16)
        ///13
        ///(5)
        ///(6)
        ///(15)
        ///(14)
        ///14
        ///(7)
        ///(9)
        ///(13)
        ///(16)
        ///15
        ///(8)
        ///(10)
        ///(13)
        ///(16)
        ///16
        ///(11)
        ///(12)
        ///(14)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HoffmanGraph {
            get {
                return ResourceManager.GetString("HoffmanGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Markström graph
        ///Number of vertices: 24
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///2
        ///(1)
        ///(9)
        ///(8)
        ///3
        ///(1)
        ///(10)
        ///(6)
        ///4
        ///(1)
        ///(7)
        ///(5)
        ///5
        ///(4)
        ///(6)
        ///(7)
        ///6
        ///(3)
        ///(5)
        ///(10)
        ///7
        ///(4)
        ///(5)
        ///(11)
        ///8
        ///(2)
        ///(13)
        ///(9)
        ///9
        ///(2)
        ///(8)
        ///(16)
        ///10
        ///(3)
        ///(6)
        ///(21)
        ///11
        ///(7)
        ///(12)
        ///(17)
        ///12
        ///(11)
        ///(14)
        ///(17)
        ///13
        ///(8)
        ///(14)
        ///(15)
        ///14
        ///(12)
        ///(13)
        ///(15)
        ///15
        ///(13)
        ///(14)
        ///(16)
        ///16
        ///(9)
        ///(15)
        ///(24)
        ///17
        ///(11)
        ///(12)
        ///(18)
        ///18
        ///(17)
        ///(20)
        ///(19)
        ///19
        ///(18)
        ///(20)
        ///(21)
        ///20
        ///(18)
        ///(19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarkstromGraph {
            get {
                return ResourceManager.GetString("MarkstromGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: McGee graph
        ///Number of vertices: 24
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(4)
        ///(5)
        ///2
        ///(1)
        ///(3)
        ///(10)
        ///3
        ///(2)
        ///(7)
        ///(22)
        ///4
        ///(1)
        ///(6)
        ///(21)
        ///5
        ///(1)
        ///(11)
        ///(16)
        ///6
        ///(4)
        ///(20)
        ///(13)
        ///7
        ///(3)
        ///(18)
        ///(19)
        ///8
        ///(9)
        ///(12)
        ///(20)
        ///9
        ///(8)
        ///(10)
        ///(17)
        ///10
        ///(2)
        ///(9)
        ///(15)
        ///11
        ///(5)
        ///(12)
        ///(14)
        ///12
        ///(8)
        ///(11)
        ///(19)
        ///13
        ///(6)
        ///(14)
        ///(18)
        ///14
        ///(13)
        ///(11)
        ///(15)
        ///15
        ///(10)
        ///(24)
        ///(14)
        ///16
        ///(5)
        ///(17)
        ///(23)
        ///17
        ///(9)
        ///(16)
        ///(18)
        ///18
        ///(7)
        ///(17)
        ///(13)
        ///19
        ///(7)
        ///(12)
        ///(21)
        ///20
        ///(6)
        ///(8)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string McGeeGraph {
            get {
                return ResourceManager.GetString("McGeeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Moser spindle
        ///Number of vertices: 7
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///2
        ///(1)
        ///(4)
        ///(6)
        ///3
        ///(1)
        ///(5)
        ///(7)
        ///4
        ///(1)
        ///(2)
        ///(6)
        ///5
        ///(1)
        ///(3)
        ///(7)
        ///6
        ///(2)
        ///(4)
        ///(7)
        ///7
        ///(3)
        ///(5)
        ///(6)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string MoserSpindle {
            get {
                return ResourceManager.GetString("MoserSpindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Poussin graph
        ///Number of vertices: 15
        ///
        ///GRAPH
        ///1
        ///(14)
        ///(2)
        ///(3)
        ///(4)
        ///(15)
        ///2
        ///(1)
        ///(3)
        ///(14)
        ///(6)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///(6)
        ///(5)
        ///(7)
        ///4
        ///(1)
        ///(3)
        ///(7)
        ///(15)
        ///5
        ///(3)
        ///(6)
        ///(7)
        ///(8)
        ///(9)
        ///6
        ///(2)
        ///(3)
        ///(5)
        ///(14)
        ///(11)
        ///(8)
        ///7
        ///(3)
        ///(4)
        ///(5)
        ///(9)
        ///(13)
        ///(15)
        ///8
        ///(5)
        ///(6)
        ///(11)
        ///(10)
        ///(9)
        ///9
        ///(5)
        ///(7)
        ///(10)
        ///(13)
        ///(8)
        ///10
        ///(8)
        ///(9)
        ///(11)
        ///(12)
        ///(13)
        ///11
        ///(6)
        ///(8)
        ///(10)
        ///(14)
        ///(12)
        ///12
        ///(10)
        ///(11)
        ///(13)
        ///(14)
        ///(15)
        ///13
        ///(7)
        ///(9)
        ///(10)
        ///(12)
        ///(15) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PoussinGraph {
            get {
                return ResourceManager.GetString("PoussinGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Robertson graph
        ///Number of vertices: 19
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(19)
        ///(5)
        ///(15)
        ///2
        ///(1)
        ///(3)
        ///(10)
        ///(13)
        ///3
        ///(2)
        ///(4)
        ///(18)
        ///(7)
        ///4
        ///(3)
        ///(16)
        ///(12)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(6)
        ///(9)
        ///6
        ///(5)
        ///(17)
        ///(13)
        ///(7)
        ///7
        ///(6)
        ///(8)
        ///(11)
        ///(3)
        ///8
        ///(7)
        ///(9)
        ///(19)
        ///(16)
        ///9
        ///(5)
        ///(8)
        ///(10)
        ///(14)
        ///10
        ///(2)
        ///(9)
        ///(11)
        ///(17)
        ///11
        ///(7)
        ///(10)
        ///(15)
        ///(12)
        ///12
        ///(4)
        ///(11)
        ///(13)
        ///(19)
        ///13
        ///(2)
        ///(6)
        ///(12)
        ///(14)
        ///14
        ///(9)
        ///(13)
        ///(18)
        ///(15)
        ///15
        ///(1)
        ///(11)
        ///(14)
        ///(16)
        ///16
        ///(4)
        ///(8)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RobertsonGraph {
            get {
                return ResourceManager.GetString("RobertsonGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Sousselier graph
        ///Number of vertices: 16
        ///
        ///GRAPH
        ///16
        ///(1)
        ///(4)
        ///(7)
        ///(10)
        ///(13)
        ///1
        ///(2)
        ///(15)
        ///(16)
        ///2
        ///(1)
        ///(12)
        ///(3)
        ///(6)
        ///3
        ///(2)
        ///(14)
        ///(4)
        ///4
        ///(3)
        ///(16)
        ///(5)
        ///5
        ///(4)
        ///(15)
        ///(6)
        ///(9)
        ///6
        ///(2)
        ///(5)
        ///(7)
        ///7
        ///(6)
        ///(16)
        ///(8)
        ///8
        ///(7)
        ///(9)
        ///(12)
        ///9
        ///(5)
        ///(8)
        ///(10)
        ///10
        ///(9)
        ///(16)
        ///(11)
        ///11
        ///(10)
        ///(15)
        ///(12)
        ///12
        ///(2)
        ///(8)
        ///(11)
        ///(13)
        ///13
        ///(12)
        ///(16)
        ///(14)
        ///15
        ///(1)
        ///(5)
        ///(11)
        ///(14)
        ///14
        ///(3)
        ///(13)
        ///(15)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string SousselierGraph {
            get {
                return ResourceManager.GetString("SousselierGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Tutte&apos;s fragment
        ///Number of vertices: 15
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///2
        ///(1)
        ///(5)
        ///(4)
        ///3
        ///(1)
        ///(4)
        ///(9)
        ///4
        ///(2)
        ///(3)
        ///(7)
        ///5
        ///(2)
        ///(6)
        ///(12)
        ///6
        ///(5)
        ///(7)
        ///(10)
        ///7
        ///(4)
        ///(6)
        ///(8)
        ///8
        ///(7)
        ///(9)
        ///(11)
        ///9
        ///(3)
        ///(8)
        ///(15)
        ///10
        ///(6)
        ///(11)
        ///(12)
        ///11
        ///(8)
        ///(10)
        ///(14)
        ///12
        ///(5)
        ///(10)
        ///(13)
        ///13
        ///(12)
        ///(14)
        ///14
        ///(11)
        ///(13)
        ///(15)
        ///15
        ///(9)
        ///(14)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string TuttesFragment {
            get {
                return ResourceManager.GetString("TuttesFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Wagner graph
        ///Number of vertices: 8
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(8)
        ///(5)
        ///2
        ///(1)
        ///(3)
        ///(6)
        ///3
        ///(2)
        ///(4)
        ///(7)
        ///4
        ///(3)
        ///(5)
        ///(8)
        ///5
        ///(4)
        ///(6)
        ///(1)
        ///6
        ///(5)
        ///(7)
        ///(2)
        ///7
        ///(6)
        ///(8)
        ///(3)
        ///8
        ///(7)
        ///(1)
        ///(4)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string WagnerGraph {
            get {
                return ResourceManager.GetString("WagnerGraph", resourceCulture);
            }
        }
    }
}
