//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TruncatedSolidsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TruncatedSolidsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources.TruncatedSolidsResource", typeof(TruncatedSolidsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Truncated cube
        ///Number of vertices: 24
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(13)
        ///(12)
        ///2
        ///(1)
        ///(3)
        ///(14)
        ///3
        ///(2)
        ///(4)
        ///(14)
        ///4
        ///(3)
        ///(5)
        ///(15)
        ///5
        ///(4)
        ///(15)
        ///(6)
        ///6
        ///(5)
        ///(16)
        ///(7)
        ///7
        ///(6)
        ///(16)
        ///(8)
        ///8
        ///(7)
        ///(17)
        ///(9)
        ///9
        ///(8)
        ///(10)
        ///(17)
        ///10
        ///(9)
        ///(18)
        ///(11)
        ///11
        ///(18)
        ///(12)
        ///(10)
        ///12
        ///(1)
        ///(11)
        ///(13)
        ///13
        ///(1)
        ///(12)
        ///(19)
        ///14
        ///(2)
        ///(3)
        ///(20)
        ///15
        ///(4)
        ///(5)
        ///(21)
        ///16
        ///(6)
        ///(7)
        ///(22)
        ///17
        ///(8)
        ///(23)
        ///(9)
        ///18
        ///(10)
        ///(11)
        ///(24)
        ///19
        ///(13)
        ///(21)
        ///(23)
        ///20
        ///(14)
        ///(22) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TruncatedCube {
            get {
                return ResourceManager.GetString("TruncatedCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: Truncated tetrahedron
        ///Number of vertices: 12
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///2
        ///(1)
        ///(4)
        ///(5)
        ///3
        ///(1)
        ///(6)
        ///(9)
        ///4
        ///(1)
        ///(2)
        ///(8)
        ///5
        ///(2)
        ///(10)
        ///(7)
        ///6
        ///(3)
        ///(7)
        ///(9)
        ///7
        ///(5)
        ///(6)
        ///(10)
        ///8
        ///(4)
        ///(11)
        ///(12)
        ///9
        ///(3)
        ///(6)
        ///(11)
        ///10
        ///(5)
        ///(7)
        ///(12)
        ///11
        ///(8)
        ///(9)
        ///(12)
        ///12
        ///(8)
        ///(10)
        ///(11)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string TruncatedTetrahedron {
            get {
                return ResourceManager.GetString("TruncatedTetrahedron", resourceCulture);
            }
        }
    }
}
