//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WheelGraphsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WheelGraphsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphColoring.GalleryOfNamedGraphs.NamedGraphsResources.WheelGraphsResource", typeof(WheelGraphsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W4
        ///Number of vertices: 4
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///2
        ///(1)
        ///(3)
        ///(4)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W4 {
            get {
                return ResourceManager.GetString("W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W5
        ///Number of vertices: 5
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///2
        ///(1)
        ///(3)
        ///(5)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W5 {
            get {
                return ResourceManager.GetString("W5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W6
        ///Number of vertices: 6
        ///
        ///GRAPH
        ///6
        ///(1)
        ///(5)
        ///(2)
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///2
        ///(1)
        ///(3)
        ///(6)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(6)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W6 {
            get {
                return ResourceManager.GetString("W6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W7
        ///Number of vertices: 7
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///2
        ///(1)
        ///(3)
        ///(7)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(6)
        ///6
        ///(1)
        ///(5)
        ///(7)
        ///7
        ///(1)
        ///(6)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W7 {
            get {
                return ResourceManager.GetString("W7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W8
        ///Number of vertices: 8
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///2
        ///(1)
        ///(3)
        ///(8)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(6)
        ///6
        ///(1)
        ///(5)
        ///(7)
        ///7
        ///(1)
        ///(6)
        ///(8)
        ///8
        ///(1)
        ///(7)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W8 {
            get {
                return ResourceManager.GetString("W8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph coloring. Graph representation: adjacencyList
        ///
        ///Graph name: W9
        ///Number of vertices: 9
        ///
        ///GRAPH
        ///1
        ///(2)
        ///(3)
        ///(4)
        ///(5)
        ///(6)
        ///(7)
        ///(8)
        ///(9)
        ///2
        ///(1)
        ///(3)
        ///(9)
        ///3
        ///(1)
        ///(2)
        ///(4)
        ///4
        ///(1)
        ///(3)
        ///(5)
        ///5
        ///(1)
        ///(4)
        ///(6)
        ///6
        ///(1)
        ///(5)
        ///(7)
        ///7
        ///(1)
        ///(6)
        ///(8)
        ///8
        ///(1)
        ///(7)
        ///(9)
        ///9
        ///(1)
        ///(8)
        ///(2)
        ///
        ///COLORED GRAPH.
        /// </summary>
        internal static string W9 {
            get {
                return ResourceManager.GetString("W9", resourceCulture);
            }
        }
    }
}
